### ISSUE TITLE
gulp-ruby-sass stuck on 0.7.1

### ISSUE THREAD

**Issue by the-james-burton** [the-james-burton/atacama#3]

**Comment by the-james-burton** [comment]
error with 2.0.6:

> [12:27:08] Starting 'styles'...
[12:27:08] 'styles' errored after 31 ms
[12:27:08] TypeError: glob pattern string required
    at new Minimatch (/home/jimsey/Development/projects/atacama/node_modules/minimatch/minimatch.js:108:11)
    at setopts (/home/jimsey/Development/projects/atacama/node_modules/glob/common.js:112:20)
    at new GlobSync (/home/jimsey/Development/projects/atacama/node_modules/glob/sync.js:38:3)
    at Function.globSync [as sync] (/home/jimsey/Development/projects/atacama/node_modules/glob/sync.js:24:10)
    at /home/jimsey/Development/projects/atacama/node_modules/gulp-ruby-sass/index.js:68:21
    at Array.forEach (native)
    at Object.gulpRubySass (/home/jimsey/Development/projects/atacama/node_modules/gulp-ruby-sass/index.js:67:10)
    at buildStyles (/home/jimsey/Development/projects/atacama/gulp/styles.js:50:13)
    at Gulp.<anonymous> (/home/jimsey/Development/projects/atacama/gulp/styles.js:20:10)
    at module.exports (/home/jimsey/Development/projects/atacama/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/home/jimsey/Development/projects/atacama/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/home/jimsey/Development/projects/atacama/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/home/jimsey/Development/projects/atacama/node_modules/orchestrator/index.js:134:8)
    at /home/jimsey/Development/software/node-v4.2.6-linux-x64/lib/node_modules/gulp/bin/gulp.js:129:20
    at nextTickCallbackWith0Args (node.js:419:9)
    at process._tickCallback (node.js:348:13)
[12:27:08] gulp-inject 5 files into index.scss.
